import { useEffect, useState } from "react";
import { listNotifications, listSubscriptions, subscribeToSpecies, unsubscribeFromSpecies } from "../../api/mediaApi";
import Field from "../../components/Field";

export default function NotificationsPanel({ onStatus }) {
  const [species, setSpecies] = useState(""); const [subscriptions, setSubscriptions] = useState([]); const [notifications, setNotifications] = useState([]);
  async function refresh() { try { const [subs, notes] = await Promise.all([listSubscriptions(), listNotifications()]); setSubscriptions(subs.species || []); setNotifications(notes.notifications || []); } catch (error) { onStatus({ type: "error", message: error.message }); } }
  useEffect(() => { refresh(); }, []);
  async function subscribe(event) { event.preventDefault(); try { await subscribeToSpecies(species.trim().toLowerCase()); setSpecies(""); onStatus({ type: "success", message: "Subscription saved." }); refresh(); } catch (error) { onStatus({ type: "error", message: error.message }); } }
  return <section className="workspace-grid"><section className="panel"><div className="panel-title"><div><p className="eyebrow">Watch a species</p><h2>Subscriptions</h2></div><span>{subscriptions.length} active</span></div><form className="inline-form" onSubmit={subscribe}><Field label="Species"><input value={species} onChange={(event) => setSpecies(event.target.value)} /></Field><button type="submit" disabled={!species.trim()}>Subscribe</button></form><div className="pill-list">{subscriptions.map((item) => <button key={item} type="button" onClick={() => unsubscribeFromSpecies(item).then(refresh).catch((error) => onStatus({ type: "error", message: error.message }))}>{item} ×</button>)}{!subscriptions.length && <p className="empty-state">No subscriptions.</p>}</div></section><section className="panel"><div className="panel-title"><div><p className="eyebrow">Recent activity</p><h2>Notifications</h2></div><button type="button" className="secondary-button" onClick={refresh}>Refresh</button></div><div className="notification-list">{notifications.map((item) => <article key={item.notification_id} className="notification-item"><strong>{item.species}</strong><span>File {item.file_id}</span><time>{new Date(item.created_at).toLocaleString()}</time></article>)}{!notifications.length && <p className="empty-state">No notifications.</p>}</div></section></section>;
}
