import { useEffect, useRef, useState } from "react";
import { listNotifications, listSubscriptions, subscribeToSpecies, unsubscribeFromSpecies } from "../../api/mediaApi";
import Field from "../../components/Field";
import { beginNotificationRefresh, normalizeNotifications, settleNotificationRefresh, shortFileId } from "../../lib/notificationState.mjs";

export default function NotificationsPanel({ onStatus }) {
  const [species, setSpecies] = useState(""); const [subscriptions, setSubscriptions] = useState([]); const [state, setState] = useState({ generation: 0, phase: "idle", items: [] }); const [busy, setBusy] = useState(false); const current = useRef(state);
  async function refresh() { const started = beginNotificationRefresh(current.current); current.current = started; setState(started); try { const [subs, notes] = await Promise.all([listSubscriptions(), listNotifications()]); const items = normalizeNotifications(notes); const next = settleNotificationRefresh(current.current, started.generation, items); if (next === current.current) return; current.current = next; setSubscriptions(Array.isArray(subs?.species) ? subs.species.filter((x) => typeof x === "string") : []); setState(next); } catch (error) { const next = settleNotificationRefresh(current.current, started.generation, [], "error"); if (next !== current.current) { current.current = next; setState(next); onStatus({ type: "error", message: error.message }); } } }
  useEffect(() => { refresh(); }, []);
  async function subscribe(event) { event.preventDefault(); if (busy || !species.trim()) return; setBusy(true); try { await subscribeToSpecies(species.trim().toLowerCase()); setSpecies(""); await refresh(); onStatus({ type: "success", message: "Subscription saved." }); } catch (error) { onStatus({ type: "error", message: error.message }); } finally { setBusy(false); } }
  async function unsubscribe(value) { if (busy) return; setBusy(true); try { await unsubscribeFromSpecies(value); await refresh(); onStatus({ type: "success", message: `Stopped watching ${value}.` }); } catch (error) { onStatus({ type: "error", message: error.message }); } finally { setBusy(false); } }
  return <section className="workspace-grid"><section className="panel"><div className="panel-title"><div><p className="eyebrow">Watch a species</p><h2>Subscriptions</h2></div><span>{subscriptions.length} active</span></div><form className="inline-form" onSubmit={subscribe}><Field label="Species"><input value={species} onChange={(event) => setSpecies(event.target.value)} /></Field><button type="submit" disabled={busy || !species.trim()}>Subscribe</button></form><div className="pill-list">{subscriptions.map((item) => <button key={item} type="button" aria-label={`Unsubscribe from ${item}`} disabled={busy} onClick={() => unsubscribe(item)}>{item} ×</button>)}{!subscriptions.length && <p className="empty-state">No subscriptions.</p>}</div></section><section className="panel"><div className="panel-title"><div><p className="eyebrow">Recent activity</p><h2>Notifications</h2></div><button type="button" className="secondary-button" disabled={busy || state.phase === "loading"} onClick={refresh}>Refresh</button></div>{state.phase === "loading" && <p className="empty-state">Loading notifications…</p>}{state.phase === "error" && <p className="empty-state">Notifications could not be loaded.</p>}<div className="notification-list">{state.phase === "ready" && state.items.map((item) => <article key={item.notification_id} className="notification-item"><strong>{item.species}</strong><span>A matching archive item is available.</span><span>File {shortFileId(item.file_id)}</span><time dateTime={item.created_at}>{new Date(item.created_at).toLocaleString()}</time>{item.object_key && <details><summary>Technical details</summary><code>{item.object_key}</code></details>}</article>)}{state.phase === "ready" && !state.items.length && <p className="empty-state">No notifications.</p>}</div></section></section>;
}
