import { useMemo, useRef, useState } from "react";
import { deleteFiles, editTags } from "../../api/mediaApi";
import ConfirmDeleteDialog from "../../components/ConfirmDeleteDialog";
import Field from "../../components/Field";
import { parseSpeciesList } from "../../lib/forms";
import { selectedMutationKeys } from "../../lib/manageSelection.mjs";
import { beginDeleteConfirmation, canSubmitTags, confirmDeleteOnce, mutationCount } from "../../lib/manageWorkflow.mjs";

export default function ManagePanel({ selectedFileIds, currentItems, onStatus, onDeleted }) {
  const [tagsText, setTagsText] = useState(""); const [operation, setOperation] = useState(1); const [deleteState, setDeleteState] = useState({ open: false, pending: false }); const deleteTrigger = useRef(null); const deleteInFlight = useRef(false);
  const keys = useMemo(() => selectedMutationKeys(selectedFileIds, currentItems), [selectedFileIds, currentItems]);
  const selectedItems = currentItems.filter((item) => selectedFileIds.includes(item.file_id) && item.can_manage);
  async function updateTags() { try { const result = await editTags(keys, parseSpeciesList(tagsText), operation); onStatus({ type: "success", message: `Updated ${mutationCount(result, keys.length, "updated")} item(s).` }); } catch (error) { onStatus({ type: "error", message: error.message }); } }
  async function confirmDelete() { if (deleteInFlight.current) return; deleteInFlight.current = true; const next = confirmDeleteOnce(deleteState); setDeleteState(next); try { const result = await deleteFiles(keys); onStatus({ type: "success", message: `Deleted ${mutationCount(result, keys.length, "deleted_db_records")} database record(s) and ${mutationCount(result, keys.length, "storage_objects_removed")} storage object(s).` }); onDeleted(selectedItems.map((item) => item.file_id)); setDeleteState({ open: false, pending: false }); } catch (error) { setDeleteState({ open: false, pending: false }); onStatus({ type: "error", message: error.message }); } finally { deleteInFlight.current = false; } }
  return <section className="panel narrow-panel"><div className="panel-title"><div><p className="eyebrow">Selected records</p><h2>Manage media</h2></div><span>{keys.length} manageable item(s)</span></div><p className="empty-state">Only selected archive records with server-provided management permission can be changed.</p><ul className="selected-id-list">{selectedItems.map((item) => <li key={item.file_id}>ID {item.file_id.slice(0, 8)}</li>)}</ul><div className="stack"><Field label="Tags"><input value={tagsText} onChange={(event) => setTagsText(event.target.value)} placeholder="wombat, dingo" /></Field><div className="segmented"><button type="button" aria-pressed={operation === 1} className={operation === 1 ? "active" : ""} onClick={() => setOperation(1)}>Add tags</button><button type="button" aria-pressed={operation === 0} className={operation === 0 ? "active" : ""} onClick={() => setOperation(0)}>Remove tags</button></div><button type="button" disabled={!keys.length || !canSubmitTags(tagsText)} onClick={updateTags}>Apply tags</button><button ref={deleteTrigger} type="button" className="danger-button" disabled={!keys.length} onClick={() => setDeleteState(beginDeleteConfirmation(deleteState))}>Delete files</button></div><ConfirmDeleteDialog open={deleteState.open} pending={deleteState.pending} count={keys.length} onCancel={() => setDeleteState({ open: false, pending: false })} onConfirm={confirmDelete} returnFocusRef={deleteTrigger} /></section>;
}
